### ISSUE TITLE
Fatal error on activation

### ISSUE THREAD

**Issue by DeveloperWil** [helmutschneider/acf-s3-content#1]
With ACF Pro v5.6.7
[03-Feb-2018 03:57:28 UTC] PHP Fatal error:  require(): Failed opening required 'C:\Projects\bitbucket\catchwhodunit.com\app\public\wp-content\plugins\acf-s3-content-master/vendor/autoload.php' (include_path='.;C:\php\pear') in C:\Projects\bitbucket\catchwhodunit.com\app\public\wp-content\plugins\acf-s3-content-master\plugin.php on line 11

**Comment by altendorfme** [comment]
Hi, enter in plugin folder and run `composer install`

**Comment by somethumb** [comment]
I'm not sure what you mean by "enter in plugin folder and run composer install"

Can you expand on these directions?

**Comment by DeveloperWil** [comment]
> I'm not sure what you mean by "enter in plugin folder and run composer install"
> 
> Can you expand on these directions?

They mean, 
1. open a command line interface (Command Prompt)
2. navigate to the plugin folder /wp-content/plugins/acf-s3-content-master/
3. in the CLI type "composer install"

This is assuming you have composer installed on your machine.  You really shouldn't need to have to do this - the developer should bundle the plugin with all the libraries needed to run it out of the box.

**Comment by helmutschneider** [comment]
Sorry guys, big disclaimer here: this package is meant for developers only. If you are looking for proper support & maintenance, look for commercial ACF plugins instead. For those wondering how to install composer, head [here](https://getcomposer.org/).

**Comment by CodeCurosity** [comment]
Why do we need to install composer? not everyone is using composer with their wordpress installation or support CLI, if you are doing this locally its fine but composer is a nightmare when you go to production mode, one small compatability issue and it brings down everything.

May you can consider adding the vendor folder?

**Comment by helmutschneider** [comment]
Agreed, composer and Wordpress is a nightmarish situation. As long as the WP-community is in conflict over that topic it's gonna be a hard nut to crack. If you need a plugin bundle including dependencies you can simply zip the repository after executing `composer install`. However, that will break too if you have other plugins depending on composer due to autoloading conflicts.

I will not commit 3rd party library code to this repository, that is out of the question.

**Comment by CodeCurosity** [comment]
If you agree then why did you choose to use composer to build this wordpress plugin?

**Comment by helmutschneider** [comment]
The plugin has dependencies (the AWS SDK) and to install dependencies you need a package manager. Composer is the de-facto package manager for PHP and that's not something I can simply "choose to not use".
